version: 1.0.{build}

environment:
  nodejs_version: "6"

build: off

cache:
  - "node_modules"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/uquyi0vrknx6qtuj/artifacts/installers%2Fcardano-node.exe' -FileName cardano-node.exe
  - mkdir node_modules\daedalus-client-api
  - cd node_modules\daedalus-client-api
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/uquyi0vrknx6qtuj/artifacts/DaedalusBridge.zip' -FileName DaedalusBridge.zip
  - 7z x DaedalusBridge.zip
  - cd ..\..\

test_script:
  - npm run package
    # TODO: DLLs
    # TODO: installer

artifacts:
  - path: release\win32-x64\Daedalus-win32-x64
    name: Daedalus
    type: zip
  # TODO: installer
